config/routes.rb
Solo::Application.routes.draw do
  get "votes/index"

  get "votes/new"

  get "votes/create"

  get "votes/destroy"

  devise_for :users
  
  resources :users
  resources :posts
  resources :votes, :only => [:create, :destroy]
  
  match 'posts/:status' => 'posts#index', :defaults => {:status => "popular"}
 
  
  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :link, :votes_count
  
  belongs_to :user
  has_many :votes, :dependent => :destroy
  
  scope :recent, order('created_at DESC')
  scope :alphabetical, order('title ASC')
  scope :popular, order('votes_count DESC')
  
 # def votes_count
#    if self.votes.count > 0
#      self.votes.count
#    else
#      0
#    end
   # read_attribute(:votes_count).presence || 0
#  end
  
#  def before_votes
#    if self.votes.count.nil?
#      self.votes.count == 0
#    end
#  end
    
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  validates_presence_of :name, :email
  validates_uniqueness_of :email, :case_sensitive => false
  
  has_many :posts, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  
  
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :user_id, :post_id
  validate :only_one_user_per_post
  
  belongs_to :user
  belongs_to :post, :counter_cache => true
  
private
  def only_one_user_per_post
    if Vote.where("user_id = ? AND post_id = ?", self.user_id, self.post_id).all.any?
      errors.add(:user_id, "Can only post once per post!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_filter :authenticate_user!, :only => [:new, :create]
	
  def index
    @vote = Vote.new(params[:vote])
      if params[:status] == "alphabetical"
        @posts = Post.alphabetical
      elsif params[:status] == "recent"
        @posts = Post.recent
      else
        @posts = Post.popular
      end
  end

	def new
	  @post = current_user.posts.build(params[:post])
	end
	
	def create
	  @post = current_user.posts.build(params[:post])
	  
    if @post.save
      flash[:success] = "Post created"
      redirect_to root_path
    else
      render 'posts/new'
    end
  end
  
	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
    redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @vote = Vote.new(params[:vote])
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(:page => params[:page])
    @post = current_user.posts.build(params[:post])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
  end

  def new
    @vote = Vote.new
    
    respond_to do |format|
      format.html
      formal.xml
    end
  end

  def create
    @vote = Vote.new(params[:vote])
    post = params[:vote][:post_id]
    @vote.user = current_user
    if @vote.save
      flash[:success] = "You voted for the article"
      redirect_to root_path
    else
      flash[:failure] = "You did not vote"
      @posts = Post.popular
      render 'posts/index'
    end
      
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>

<%= link_to "Recent", recent_path %>
<%= link_to "Popular", popular_path %>

<%= render :partial => 'shared/post', :collection => @posts %>

<% end %>

app/views/home/stories.html.erb
<h3>Story 1</h3>

<h3>Story 2</h3>

<h3>Story 3</h3>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Solo</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application" %>
	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
	<%= stylesheet_link_tag    "custom" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller] %>">
    <div id="container">
      <header>
        <nav>
		<div class="topbar">
		<div class="fill">
		<div class="container">
		<h3><%= link_to "Learning Quotient", posts_path %></h3>
		<ul>
            <%= render 'shared/navigation' %>
		</ul>
		</div>
		</div>
		</div>
        </nav>
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String) %>
        <%- end -%>
      </header>
      <div id="main" role="main" class="container">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/posts/_post.html.erb
<tr>
<div class="post">
	<blockquote>
	<%= form_for @vote do |f| %>
	<div class="right">	<%= image_submit_tag "plus32.png", :size => "16x16", :class => "squareicon" %>
	<span class="label success"><%= post.votes_count %></span>
	</div>
	<div id="postbody">
	<% if post.title %>
	<h3><%= link_to post.title, post.link %></h3>
	<% end %>
	<p><%= post.content %></p>
	<small><%= link_to post.user.name, post.user %></small>
	<% if user_signed_in? %>
	<% if current_user == @user %>
    <%= link_to "delete", post, :method => :delete,
                                :confirm => "You sure?",
 								:class => "danger btn"%>
	<% end %>
	<% end %>
	</div>
	<%= f.hidden_field "post_id", :value => post.id %>

	<% end %>
	</blockquote>
</div>
</tr>

app/views/posts/index.html.erb
<ul class="pills">
<% if params[:status] == "popular"%>
	<li class="active">
<% else %>
	<li>
<% end %>
	<%= link_to "Popular", :controller => "posts", :status => "popular" %></li>
<% if params[:status] == "recent" %>
	<li class="active">
<% else %>
	<li>
<% end %>
	<%= link_to "Recent", :controller => "posts", :status => "recent" %></li>
<% if params[:status] == "alphabetical" %>
	<li class="active">
<% else %>
	<li>
	<% end %>
<%= link_to "Alphabetical", :controller => "posts", :status => "alphabetical" %></l1>
<li><%= link_to "New", :controller => "posts", :action => "new" %></li>
</ul>

<% flash.each do |key, value| %>
	<div class="flash <%= key %>"><%= value %></div>
<% end %>

<table class="posts" summary="User posts">
	<%= render @posts %>
</table>

app/views/posts/new.html.erb
<ul class="pills">
<li><%= link_to "Recent", :controller => "posts", :status => "recent" %></li>
<li><%= link_to "Alphabetical", :controller => "posts", :status => "alphabetical" %></l1>
<li class="active"><%= link_to "New", :controller => "posts", :action => "new" %></li>
</ul>

Write a new post:
<%= render 'shared/post_form' %>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title, "Title"%>
  	<%= f.text_field :title %>
	<br />
	<%= f.label :link, "URL" %>
	<%= f.url_field :link %>
	<br />
	<div class="field">
	<%= f.label :content, "Text" %><br />
    <%= f.text_area :content %>
  	</div>
  	<div>
    <%= f.submit "Submit", :class => "btn" %>
  	</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Posts</h1>
<% unless @user.posts.empty? %>
	<table class="posts" summary="User posts">
		<%= render @posts %>
	</table>
<% end %>

	

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.js.erb
$(document).ready(function(){
 
    alert('This is a pathetically simple AJAX response!');
 
});

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/index.html.erb
<h1>Votes#index</h1>
<p>Find me in app/views/votes/index.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>